import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <div className="w-screen min-h-screen">
            <Head>
                <title>Home | MfundiRez Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex overflow-hidden">
                <section className="flex flex-col items-center justify-center">
                    <h1 className="text-4xl mb-5 font-bold italic tracking-wider">
                        MfundiRez Registration
                    </h1>

                    <img src="home.svg" alt="" className="w-1/2 my-7" />

                    <p className="text-lg p-10">
                        Are you a student looking for accommodation? Come join us at{" "}
                        <span className="font-bold">MfundiRez</span> - Your home away from home.
                    </p>

                    <Link href={"/application/step-one"}>
                        <button className="inline-flex w-2/3 justify-center py-2 px-4 mt-3 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-amber-500 hover:bg-amber-600 focus:outline-none">
                            Apply Now
                        </button>
                    </Link>
                </section>
                <img src="/image.jpg" alt="" className="w-3/5 h-screen" />
            </main>
        </div>
    );
};

export default Home;
