import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Registration | PSA Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>PSA Registration</h1>

            <p>
                Are you a student looking for accommodation? Come join us at Premier Student
                Accommodation - Your home away from home.
            </p>

            <Link href={"/application/step-one"}>
                <button className="inline-flex justify-center py-2 px-4 mt-3 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-red-600 hover:bg-red-700 focus:outline-none">
                    Apply Now
                </button>
            </Link>
        </div>
    );
};

export default Home;
